FROM nginx:1.25.2

LABEL version="1.0"

RUN apt update -y && apt install libfcgi-dev -y && apt install spawn-fcgi -y && apt install gcc -y && rm -rf /var/lib/apt/lists

COPY ./server/main.c /usr/share/nginx/main.c
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./run.sh /usr/share/nginx/run.sh

RUN find /usr/bin -type f -perm /4000 ! -perm /2000 -exec chmod u-s {} +
RUN find /usr/bin -type f -perm /2000 ! -perm /4000 -exec chmod g-s {} +
RUN find /usr/sbin -type f -perm /2000 ! -perm /4000 -exec chmod g-s {} +

WORKDIR /usr/share/nginx/
USER nginx

ENTRYPOINT service nginx start && /usr/share/nginx/run.sh

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1

# sudo docker run -d -p 80:81 -u root -v ./nginx/:/etc/nginx custom_server:1.0
# sudo docker build -t custom_server:1.0 .
# sudo dockle -ak NGINX_GPGKEY -ak NGINX_GPGKEY_PATH custom_server:1.0